# Generated by Django 5.2.7 on 2025-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_is_active_alter_user_is_seeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of your skills', max_length=255, null=True),
        ),
    ]
