# Generated by Django 5.2.7 on 2025-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_seekerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='resume_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
