# Generated by Django 5.2.7 on 2025-11-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_seekerprofile_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
