services:
  - type: web
    name: jobportal
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn jobportal.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SITE_DOMAIN
        sync: false
