# Generated by Django 5.2.7 on 2025-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
