# Generated by Django 5.2.7 on 2025-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_cover_letter_application_github_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
