# Generated by Django 5.2.7 on 2025-10-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='require_cover_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='require_github',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='require_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='require_resume',
            field=models.BooleanField(default=True),
        ),
    ]
