# Generated by Django 5.2.7 on 2025-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_require_cover_letter_job_require_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='General', help_text='Comma-separated list of required skills', max_length=255),
            preserve_default=False,
        ),
    ]
